//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Observer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sdi.observerIce;

/** @hidden */
public class _TriggerPrxI extends com.zeroc.Ice._ObjectPrxI implements TriggerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
