//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Cifrador.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sdi.cifradorIce;

/** @hidden */
public class _CifradorPrxI extends com.zeroc.Ice._ObjectPrxI implements CifradorPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
