//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `robot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package agencia.objetos;

/** @hidden */
public class _CamaraPrxI extends com.zeroc.Ice._ObjectPrxI implements CamaraPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
