//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `robot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package agencia.objetos;

public interface CamaraPrx extends com.zeroc.Ice.ObjectPrx
{
    default agencia.datos.suscripcion SuscribirRobot(String IORrob)
    {
        return SuscribirRobot(IORrob, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default agencia.datos.suscripcion SuscribirRobot(String IORrob, java.util.Map<String, String> context)
    {
        return _iceI_SuscribirRobotAsync(IORrob, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.suscripcion> SuscribirRobotAsync(String IORrob)
    {
        return _iceI_SuscribirRobotAsync(IORrob, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.suscripcion> SuscribirRobotAsync(String IORrob, java.util.Map<String, String> context)
    {
        return _iceI_SuscribirRobotAsync(IORrob, context, false);
    }

    /**
     * @hidden
     * @param iceP_IORrob -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<agencia.datos.suscripcion> _iceI_SuscribirRobotAsync(String iceP_IORrob, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<agencia.datos.suscripcion> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "SuscribirRobot", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_IORrob);
                 }, istr -> {
                     agencia.datos.suscripcion ret;
                     ret = agencia.datos.suscripcion.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default agencia.datos.suscripcion SuscribirConsola(String IORcons)
    {
        return SuscribirConsola(IORcons, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default agencia.datos.suscripcion SuscribirConsola(String IORcons, java.util.Map<String, String> context)
    {
        return _iceI_SuscribirConsolaAsync(IORcons, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.suscripcion> SuscribirConsolaAsync(String IORcons)
    {
        return _iceI_SuscribirConsolaAsync(IORcons, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.suscripcion> SuscribirConsolaAsync(String IORcons, java.util.Map<String, String> context)
    {
        return _iceI_SuscribirConsolaAsync(IORcons, context, false);
    }

    /**
     * @hidden
     * @param iceP_IORcons -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<agencia.datos.suscripcion> _iceI_SuscribirConsolaAsync(String iceP_IORcons, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<agencia.datos.suscripcion> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "SuscribirConsola", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_IORcons);
                 }, istr -> {
                     agencia.datos.suscripcion ret;
                     ret = agencia.datos.suscripcion.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void BajaRobot(String IORrob)
    {
        BajaRobot(IORrob, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void BajaRobot(String IORrob, java.util.Map<String, String> context)
    {
        _iceI_BajaRobotAsync(IORrob, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> BajaRobotAsync(String IORrob)
    {
        return _iceI_BajaRobotAsync(IORrob, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> BajaRobotAsync(String IORrob, java.util.Map<String, String> context)
    {
        return _iceI_BajaRobotAsync(IORrob, context, false);
    }

    /**
     * @hidden
     * @param iceP_IORrob -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_BajaRobotAsync(String iceP_IORrob, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "BajaRobot", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_IORrob);
                 }, null);
        return f;
    }

    default void BajaConsola(String IORcons)
    {
        BajaConsola(IORcons, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void BajaConsola(String IORcons, java.util.Map<String, String> context)
    {
        _iceI_BajaConsolaAsync(IORcons, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> BajaConsolaAsync(String IORcons)
    {
        return _iceI_BajaConsolaAsync(IORcons, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> BajaConsolaAsync(String IORcons, java.util.Map<String, String> context)
    {
        return _iceI_BajaConsolaAsync(IORcons, context, false);
    }

    /**
     * @hidden
     * @param iceP_IORcons -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_BajaConsolaAsync(String iceP_IORcons, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "BajaConsola", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_IORcons);
                 }, null);
        return f;
    }

    default agencia.datos.ListaSuscripcion ObtenerLista()
    {
        return ObtenerLista(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default agencia.datos.ListaSuscripcion ObtenerLista(java.util.Map<String, String> context)
    {
        return _iceI_ObtenerListaAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.ListaSuscripcion> ObtenerListaAsync()
    {
        return _iceI_ObtenerListaAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.ListaSuscripcion> ObtenerListaAsync(java.util.Map<String, String> context)
    {
        return _iceI_ObtenerListaAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<agencia.datos.ListaSuscripcion> _iceI_ObtenerListaAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<agencia.datos.ListaSuscripcion> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ObtenerLista", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     agencia.datos.ListaSuscripcion ret;
                     ret = agencia.datos.ListaSuscripcion.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default agencia.datos.IPYPort ObtenerIPYPortDifusion()
    {
        return ObtenerIPYPortDifusion(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default agencia.datos.IPYPort ObtenerIPYPortDifusion(java.util.Map<String, String> context)
    {
        return _iceI_ObtenerIPYPortDifusionAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.IPYPort> ObtenerIPYPortDifusionAsync()
    {
        return _iceI_ObtenerIPYPortDifusionAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.IPYPort> ObtenerIPYPortDifusionAsync(java.util.Map<String, String> context)
    {
        return _iceI_ObtenerIPYPortDifusionAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<agencia.datos.IPYPort> _iceI_ObtenerIPYPortDifusionAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<agencia.datos.IPYPort> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ObtenerIPYPortDifusion", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     agencia.datos.IPYPort ret;
                     ret = agencia.datos.IPYPort.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default agencia.datos.Instantanea ObtenerInstantanea()
    {
        return ObtenerInstantanea(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default agencia.datos.Instantanea ObtenerInstantanea(java.util.Map<String, String> context)
    {
        return _iceI_ObtenerInstantaneaAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.Instantanea> ObtenerInstantaneaAsync()
    {
        return _iceI_ObtenerInstantaneaAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.Instantanea> ObtenerInstantaneaAsync(java.util.Map<String, String> context)
    {
        return _iceI_ObtenerInstantaneaAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<agencia.datos.Instantanea> _iceI_ObtenerInstantaneaAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<agencia.datos.Instantanea> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ObtenerInstantanea", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     agencia.datos.Instantanea ret;
                     ret = agencia.datos.Instantanea.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void ModificarEscenario(agencia.datos.Escenario esc)
    {
        ModificarEscenario(esc, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void ModificarEscenario(agencia.datos.Escenario esc, java.util.Map<String, String> context)
    {
        _iceI_ModificarEscenarioAsync(esc, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> ModificarEscenarioAsync(agencia.datos.Escenario esc)
    {
        return _iceI_ModificarEscenarioAsync(esc, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> ModificarEscenarioAsync(agencia.datos.Escenario esc, java.util.Map<String, String> context)
    {
        return _iceI_ModificarEscenarioAsync(esc, context, false);
    }

    /**
     * @hidden
     * @param iceP_esc -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_ModificarEscenarioAsync(agencia.datos.Escenario iceP_esc, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ModificarEscenario", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     agencia.datos.Escenario.ice_write(ostr, iceP_esc);
                 }, null);
        return f;
    }

    default agencia.datos.Escenario ObtenerEscenario()
    {
        return ObtenerEscenario(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default agencia.datos.Escenario ObtenerEscenario(java.util.Map<String, String> context)
    {
        return _iceI_ObtenerEscenarioAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.Escenario> ObtenerEscenarioAsync()
    {
        return _iceI_ObtenerEscenarioAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<agencia.datos.Escenario> ObtenerEscenarioAsync(java.util.Map<String, String> context)
    {
        return _iceI_ObtenerEscenarioAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<agencia.datos.Escenario> _iceI_ObtenerEscenarioAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<agencia.datos.Escenario> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ObtenerEscenario", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     agencia.datos.Escenario ret;
                     ret = agencia.datos.Escenario.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CamaraPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), CamaraPrx.class, _CamaraPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CamaraPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), CamaraPrx.class, _CamaraPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CamaraPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), CamaraPrx.class, _CamaraPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CamaraPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), CamaraPrx.class, _CamaraPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static CamaraPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, CamaraPrx.class, _CamaraPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static CamaraPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, CamaraPrx.class, _CamaraPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default CamaraPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (CamaraPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default CamaraPrx ice_adapterId(String newAdapterId)
    {
        return (CamaraPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default CamaraPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (CamaraPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default CamaraPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (CamaraPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default CamaraPrx ice_invocationTimeout(int newTimeout)
    {
        return (CamaraPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default CamaraPrx ice_connectionCached(boolean newCache)
    {
        return (CamaraPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default CamaraPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (CamaraPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CamaraPrx ice_secure(boolean b)
    {
        return (CamaraPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default CamaraPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (CamaraPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CamaraPrx ice_preferSecure(boolean b)
    {
        return (CamaraPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default CamaraPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (CamaraPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default CamaraPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (CamaraPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default CamaraPrx ice_collocationOptimized(boolean b)
    {
        return (CamaraPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default CamaraPrx ice_twoway()
    {
        return (CamaraPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default CamaraPrx ice_oneway()
    {
        return (CamaraPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default CamaraPrx ice_batchOneway()
    {
        return (CamaraPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default CamaraPrx ice_datagram()
    {
        return (CamaraPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default CamaraPrx ice_batchDatagram()
    {
        return (CamaraPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default CamaraPrx ice_compress(boolean co)
    {
        return (CamaraPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default CamaraPrx ice_timeout(int t)
    {
        return (CamaraPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default CamaraPrx ice_connectionId(String connectionId)
    {
        return (CamaraPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default CamaraPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (CamaraPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::agencia::objetos::Camara";
    }
}
