//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `robot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package agencia.objetos;

public interface RobotSeguidor extends com.zeroc.Ice.Object
{
    agencia.datos.EstadoRobot ObtenerEstado(com.zeroc.Ice.Current current);

    void ModificarEscenario(agencia.datos.Escenario esc, com.zeroc.Ice.Current current);

    void ModificarObjetivo(agencia.datos.Posicion NuevoObj, com.zeroc.Ice.Current current);

    void ModificarPosicion(agencia.datos.Posicion npos, com.zeroc.Ice.Current current);

    void ModificarLider(int idLider, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::agencia::objetos::RobotSeguidor"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::agencia::objetos::RobotSeguidor";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_ObtenerEstado(RobotSeguidor obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        agencia.datos.EstadoRobot ret = obj.ObtenerEstado(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        agencia.datos.EstadoRobot.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_ModificarEscenario(RobotSeguidor obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        agencia.datos.Escenario iceP_esc;
        iceP_esc = agencia.datos.Escenario.ice_read(istr);
        inS.endReadParams();
        obj.ModificarEscenario(iceP_esc, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_ModificarObjetivo(RobotSeguidor obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        agencia.datos.Posicion iceP_NuevoObj;
        iceP_NuevoObj = agencia.datos.Posicion.ice_read(istr);
        inS.endReadParams();
        obj.ModificarObjetivo(iceP_NuevoObj, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_ModificarPosicion(RobotSeguidor obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        agencia.datos.Posicion iceP_npos;
        iceP_npos = agencia.datos.Posicion.ice_read(istr);
        inS.endReadParams();
        obj.ModificarPosicion(iceP_npos, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_ModificarLider(RobotSeguidor obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_idLider;
        iceP_idLider = istr.readInt();
        inS.endReadParams();
        obj.ModificarLider(iceP_idLider, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "ModificarEscenario",
        "ModificarLider",
        "ModificarObjetivo",
        "ModificarPosicion",
        "ObtenerEstado",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_ModificarEscenario(this, in, current);
            }
            case 1:
            {
                return _iceD_ModificarLider(this, in, current);
            }
            case 2:
            {
                return _iceD_ModificarObjetivo(this, in, current);
            }
            case 3:
            {
                return _iceD_ModificarPosicion(this, in, current);
            }
            case 4:
            {
                return _iceD_ObtenerEstado(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
