//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `robot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package agencia.datos;

public class ListaSuscripcion implements java.lang.Cloneable,
                                         java.io.Serializable
{
    public String[] IORrobots;

    public String[] IORconsolas;

    public ListaSuscripcion()
    {
    }

    public ListaSuscripcion(String[] IORrobots, String[] IORconsolas)
    {
        this.IORrobots = IORrobots;
        this.IORconsolas = IORconsolas;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ListaSuscripcion r = null;
        if(rhs instanceof ListaSuscripcion)
        {
            r = (ListaSuscripcion)rhs;
        }

        if(r != null)
        {
            if(!java.util.Arrays.equals(this.IORrobots, r.IORrobots))
            {
                return false;
            }
            if(!java.util.Arrays.equals(this.IORconsolas, r.IORconsolas))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::agencia::datos::ListaSuscripcion");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, IORrobots);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, IORconsolas);
        return h_;
    }

    public ListaSuscripcion clone()
    {
        ListaSuscripcion c = null;
        try
        {
            c = (ListaSuscripcion)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeStringSeq(this.IORrobots);
        ostr.writeStringSeq(this.IORconsolas);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.IORrobots = istr.readStringSeq();
        this.IORconsolas = istr.readStringSeq();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ListaSuscripcion v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ListaSuscripcion ice_read(com.zeroc.Ice.InputStream istr)
    {
        ListaSuscripcion v = new ListaSuscripcion();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ListaSuscripcion> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ListaSuscripcion v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ListaSuscripcion> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ListaSuscripcion.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ListaSuscripcion _nullMarshalValue = new ListaSuscripcion();

    /** @hidden */
    public static final long serialVersionUID = 6873964058828240834L;
}
