//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `robot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package agencia.datos;

public class Rectangulo implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public float x;

    public float y;

    public float ancho;

    public float alto;

    public int color;

    public Rectangulo()
    {
    }

    public Rectangulo(float x, float y, float ancho, float alto, int color)
    {
        this.x = x;
        this.y = y;
        this.ancho = ancho;
        this.alto = alto;
        this.color = color;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Rectangulo r = null;
        if(rhs instanceof Rectangulo)
        {
            r = (Rectangulo)rhs;
        }

        if(r != null)
        {
            if(this.x != r.x)
            {
                return false;
            }
            if(this.y != r.y)
            {
                return false;
            }
            if(this.ancho != r.ancho)
            {
                return false;
            }
            if(this.alto != r.alto)
            {
                return false;
            }
            if(this.color != r.color)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::agencia::datos::Rectangulo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, x);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, y);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ancho);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, alto);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, color);
        return h_;
    }

    public Rectangulo clone()
    {
        Rectangulo c = null;
        try
        {
            c = (Rectangulo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeFloat(this.x);
        ostr.writeFloat(this.y);
        ostr.writeFloat(this.ancho);
        ostr.writeFloat(this.alto);
        ostr.writeInt(this.color);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.x = istr.readFloat();
        this.y = istr.readFloat();
        this.ancho = istr.readFloat();
        this.alto = istr.readFloat();
        this.color = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Rectangulo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Rectangulo ice_read(com.zeroc.Ice.InputStream istr)
    {
        Rectangulo v = new Rectangulo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Rectangulo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Rectangulo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(20);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Rectangulo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Rectangulo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Rectangulo _nullMarshalValue = new Rectangulo();

    /** @hidden */
    public static final long serialVersionUID = 4447147080460074776L;
}
